### ISSUE TITLE
feature/auth - User authentication

### ISSUE THREAD

**Issue by pum-khoa** [Triply-Organization/frontend#2]
#### Đăng nhập

- [x] Lập trình giao diện đăng nhập
- [x] Validate form và gửi thông tin đến database:
```js
// request
email: String,
password: String,

// response
??
```
- [x] Backend xử lý thông tin để trả lại thông tin người dùng và trạng thái đã đăng nhập
- [x] Bắt lỗi không tồn tại username
- [x] Bắt lỗi không đúng password

### Đăng ký

- [x] Lập trình giao diện đăng ký
- [x] Validate from và gửi thông tin đến database:
```js
// request
email: String,
name: String,
password: String,
role: 'customer' || 'user'

// response

```
- [x] Bắt lỗi đã tồn tại email
- [x] Backend xử lý thông tin, xác thực email
- [ ] Lập trình giao diện đăng ký - Xác thực email
- [x] Bắt lỗi mã xác thực không đúng

**Comment by nguyendangnfq** [comment]
Do we use ANTD to validate or pure validate ?

**Comment by pum-khoa** [comment]
https://github.com/Triply-Organization/frontend/issues/2#issuecomment-1167011732
Yeah, we already install AntD, which you can use!

**Comment by nguyendangnfq** [comment]
ok I got it thanks for ur response

**Comment by nhivo1203** [comment]
request of register should be "name" : string , it includes "firstName" and "lastName"

**Comment by nguyendangnfq** [comment]
### Login page: 


![Image](https://user-images.githubusercontent.com/104899842/176365880-fd4cd654-2aeb-4c05-9a06-be2206f04eec.png)


### Register page - User Info: 


![Image](https://user-images.githubusercontent.com/104899842/176365969-ef042d3a-23b9-475f-9895-8d675cee4616.png)


### Register page - Choose role:
- after validate and fill all form input


![Image](https://user-images.githubusercontent.com/104899842/176366051-5181b813-adcc-4d0f-bd26-eb4702dbae80.png)
